
-- ============================================================
-- PrisHistorie PostgreSQL baseline schema
-- Replaces the old SQLite schema.
-- cars and inactivecars are merged into a single cars table.
-- ============================================================


-- ------------------------------------------------------------
-- Fuel types
--
-- Faste ID-er beholdes fra dagens database.
-- ------------------------------------------------------------

CREATE TABLE fuel_types (
    id INTEGER PRIMARY KEY,
    type TEXT NOT NULL UNIQUE
);


-- ------------------------------------------------------------
-- Dealer segments
--
-- Faste ID-er beholdes fra dagens database.
-- ------------------------------------------------------------

CREATE TABLE dealer_segment (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);


-- ------------------------------------------------------------
-- Body types
--
-- Nye body types kan opprettes dynamisk av applikasjonen.
-- ------------------------------------------------------------

CREATE TABLE body_type (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body_type TEXT NOT NULL UNIQUE
);


-- ------------------------------------------------------------
-- Cars / ads
--
-- Erstatter både SQLite-tabellene:
--   cars
--   inactivecars
--
-- car_id er ID-en på annonsen.
-- ------------------------------------------------------------

CREATE TABLE cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Ekstern annonse-ID
    car_id BIGINT NOT NULL UNIQUE,

    -- Bildata
    make TEXT,
    model TEXT,
    year INTEGER,
    km INTEGER,
    gear TEXT,

    fuel_type_id INTEGER,
    vin TEXT,

    free_text_model TEXT,
    reg_no TEXT,

    location TEXT,
    url TEXT,

    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,

    image_link TEXT,

    dealer_segment_id INTEGER,
    organisation_name TEXT,

    -- Timestamp hentet direkte fra nettsiden.
    -- Unix epoch i millisekunder, f.eks. 1787903486000.
    ad_timestamp BIGINT,

    body_type_id INTEGER,

    -- Når PrisHistorie først observerte annonsen.
    first_seen_at TIMESTAMPTZ,

    -- --------------------------------------------------------
    -- Status på selve annonsen
    --
    -- Eksempler:
    -- active
    -- sold
    -- inactive
    -- unavailable
    -- not_found
    --
    -- inactive beholdes bl.a. for gamle data der vi ikke vet
    -- hvilken type inaktivitet som faktisk ble observert.
    -- --------------------------------------------------------

    ad_status TEXT NOT NULL DEFAULT 'active',

    -- Når vi observerte statusendringen.
    ad_status_changed_at TIMESTAMPTZ,

    -- Mer presis observasjon, f.eks.
    -- explicit_sold
    -- http_404
    -- message_not_available
    ad_status_detail TEXT,

    -- --------------------------------------------------------
    -- PrisHistorie sin konklusjon
    --
    -- Eksempler:
    -- sold
    -- likely_timeout
    -- unknown
    --
    -- Dette holdes separat fra ad_status fordi en annonse
    -- kan forsvinne uten at bilen nødvendigvis er solgt.
    -- --------------------------------------------------------

    outcome TEXT,

    -- Hvor konklusjonen kommer fra, f.eks.
    -- ad
    -- vehicle_registry
    -- inference
    outcome_source TEXT,

    -- --------------------------------------------------------
    -- Informasjon fra Vegvesenet
    --
    -- Eksempler:
    -- registered
    -- temporarily_deregistered
    -- permanently_deregistered
    -- --------------------------------------------------------

    vehicle_status TEXT,

    vehicle_status_checked_at TIMESTAMPTZ,

    -- Om vi har funnet et nylig eierskifte.
    ownership_changed BOOLEAN,

    ownership_checked_at TIMESTAMPTZ,


    CONSTRAINT fk_cars_fuel_type
        FOREIGN KEY (fuel_type_id)
        REFERENCES fuel_types(id),

    CONSTRAINT fk_cars_dealer_segment
        FOREIGN KEY (dealer_segment_id)
        REFERENCES dealer_segment(id),

    CONSTRAINT fk_cars_body_type
        FOREIGN KEY (body_type_id)
        REFERENCES body_type(id)
);


-- ------------------------------------------------------------
-- Prices
--
-- Prishistorikken tilhører annonsen via car_id.
-- En annonse beholder prisene selv om den blir solgt,
-- utilgjengelig eller slettet.
-- ------------------------------------------------------------

CREATE TABLE prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    car_id BIGINT NOT NULL,

    -- Hele kroner.
    price INTEGER NOT NULL,

    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_prices_car
        FOREIGN KEY (car_id)
        REFERENCES cars(car_id)
);


-- ------------------------------------------------------------
-- Status check progress
--
-- Brukes av batch-jobben for å huske hvor langt den har kommet.
-- ------------------------------------------------------------

CREATE TABLE status_check_progress (
    id INTEGER PRIMARY KEY CHECK (id = 1),

    last_processed_car_id BIGINT NOT NULL DEFAULT 0,

    last_run_timestamp TIMESTAMPTZ,

    total_cars_processed BIGINT NOT NULL DEFAULT 0,

    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO status_check_progress (id)
VALUES (1)
ON CONFLICT (id) DO NOTHING;


-- ============================================================
-- Indexes
-- ============================================================

-- car_id får allerede indeks automatisk fordi den er UNIQUE.


-- Vanlig bruk:
-- SELECT price
-- FROM prices
-- WHERE car_id = ...
-- ORDER BY timestamp DESC
-- LIMIT 1;

CREATE INDEX idx_prices_car_timestamp
    ON prices (car_id, timestamp DESC);


-- Nyttig for søk på aktive/inaktive/solgte annonser.

CREATE INDEX idx_cars_ad_status
    ON cars (ad_status);


-- Nyttig for tidsbaserte spørringer.

CREATE INDEX idx_cars_first_seen_at
    ON cars (first_seen_at);
