{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: {{ .Values.postgres.persistence.claimName }}
  namespace: {{ .Release.Namespace }}

spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}

  storageClassName: {{ .Values.postgres.persistence.storageClass }}

  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
{{- end }}        