apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prishistorie-postgres-backup
  namespace: prishistorie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi