kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 31072
        hostPort: 31072
        protocol: TCP
      - containerPort: 31063
        hostPort: 31063
        protocol: TCP

  - role: worker
  - role: worker

networking:
  disableDefaultCNI: true