apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prishistorie-postgres
  namespace: prishistorie
spec:
  serviceName: prishistorie-postgres
  replicas: 1

  selector:
    matchLabels:
      app: prishistorie-postgres

  template:
    metadata:
      labels:
        app: prishistorie-postgres

    spec:
      containers:
        - name: postgres
          image: postgres:17

          ports:
            - containerPort:  {{ .Values.postgres.service.port }}

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: prishistorie-postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: prishistorie-postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prishistorie-postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: prishistorie-postgres-data
