apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prishistorie-data
  namespace: prishistorie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi