apiVersion: v1
kind: Secret
metadata:
  name: prishistorie-secrets
  namespace: prishistorie
type: Opaque
stringData:
  KJORETOY_API_KEY: "<api-key>"
  RECIPIENT_EMAIL: "<recipient-email>"
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"
  SENDER_EMAIL: "<sender-email>"
  SENDER_PASSWORD: "<password>"